############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
weight = 2

[[main]]
parent = 'About'
name = "About the Project"
url = "/about"
weight = 1

[[main]]
parent = 'About'
name = "People"
url = "/authors"
weight = 2

[[main]]
name = "Resources"
weight = 3

[[main]]
parent =  'Resources'
name = "For Students"
url = "resources-for-students"
weight = 1

[[main]]
parent =  'Resources'
name = "For Teachers"
url = "resources-for-teachers"
weight = 2

[[main]]
parent =  'Resources'
name = "For Parents"
url = "resources-for-parents"
weight = 3

#[[main]]
#name = "Blog"
#url = "/blog"
#weight = 4

[[main]]
name = "Community"
weight = 4
url = "/community"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
